CREATE TABLE paciente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    endereco VARCHAR(255) NOT NULL,
    telefone VARCHAR(255) NOT NULL,
    cpf VARCHAR(255) UNIQUE,
    data_nascimento DATE,
    data_criacao DATE,
    ativo BOOLEAN NOT NULL,
    convenio VARCHAR(255),
    profissao VARCHAR(255),
    nome_pai VARCHAR(255),
    nome_mae VARCHAR(255),
    sexo VARCHAR(255)
);

CREATE TABLE consulta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora TIMESTAMP,
    duracao_minutos INTEGER,
    valor NUMERIC(19, 2),
    status VARCHAR(255),
    tipo VARCHAR(255),
    observacoes VARCHAR(255),
    paciente_id BIGINT,
    CONSTRAINT fk_consulta_paciente FOREIGN KEY (paciente_id) REFERENCES paciente (id)
);

CREATE TABLE lancamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(255),
    valor NUMERIC(19, 2),
    data DATE,
    tipo VARCHAR(255),
    paciente_id BIGINT,
    CONSTRAINT fk_lancamento_paciente FOREIGN KEY (paciente_id) REFERENCES paciente (id)
);

CREATE TABLE avaliacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id BIGINT,
    status VARCHAR(255),
    data_inicio DATE,
    data_laudo DATE,
    data_devolutiva DATE,
    ativo BOOLEAN,
    CONSTRAINT fk_avaliacao_paciente FOREIGN KEY (paciente_id) REFERENCES paciente (id)
);

CREATE TABLE anotacao_paciente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_criacao TIMESTAMP,
    observacao VARCHAR(5000),
    paciente_id BIGINT,
    CONSTRAINT fk_anotacao_paciente FOREIGN KEY (paciente_id) REFERENCES paciente (id)
);
