CREATE TABLE teste_psicologico (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome           VARCHAR(255) NOT NULL,
    qtd_estoque    INTEGER      NOT NULL,
    estoque_minimo INTEGER      NOT NULL,
    custo_unitario NUMERIC(10,2) NOT NULL,
    ativo          BOOLEAN      NOT NULL
);

INSERT INTO teste_psicologico (nome, qtd_estoque, estoque_minimo, custo_unitario, ativo)
VALUES ('WISC-IV', 10, 3, 45.00, TRUE);

INSERT INTO teste_psicologico (nome, qtd_estoque, estoque_minimo, custo_unitario, ativo)
VALUES ('Teste Inativo', 0, 2, 30.00, FALSE);